Updated is_reference to reference to match release 102 metadata schema
Ensembl/ensembl-metadata-registry pull request #7
Opened 2020-05-27 12:57 UTC by thomasmaurel

This is to match code changes for 102 here: https://github.com/Ensembl/ensembl-metadata/pull/99/files

2020-05-27 13:01 UTC, marcoooo requested changes
May be you should include a migration file as well, right ? `./manage.py makemigrations` should do ?

2020-05-27 14:57 UTC, thomasmaurel commented
> May be you should include a migration file as well, right ? `./manage.py makemigrations` should do ?

Yes very good point, I will push a migration file

2020-05-28 13:14 UTC, thomasmaurel commented
> May be you should include a migration file as well, right ? `./manage.py makemigrations` should do ?

As discussed there are not migration files at the moment, we will need to do that in an other development Sprint

2020-05-28 15:23 UTC, marcoooo approved these changes

2020-05-28 15:39 UTC, merged